# Generated by Django 3.2.7 on 2021-10-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videolink', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videolink', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videolink', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='yoga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videolink', models.CharField(max_length=100)),
            ],
        ),
    ]
