# Generated by Django 3.0.8 on 2021-11-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0004_auto_20211102_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='filesupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('profile', models.FileField(upload_to='dietfiles')),
            ],
        ),
    ]
